apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-techdocs-demo
  description: An example of TechDocs.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: backstage/maintainers
  lifecycle: experimental
